-- Create users table
CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE
);

-- Create index on username for faster lookups
CREATE INDEX IF NOT EXISTS IDX_USERS_USERNAME ON USERS(USERNAME);

-- Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS IDX_USERS_EMAIL ON USERS(EMAIL);

