CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
    ENABLED BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS IDX_USERS_USERNAME ON USERS(USERNAME);

CREATE INDEX IF NOT EXISTS IDX_USERS_EMAIL ON USERS(EMAIL);

CREATE TABLE IF NOT EXISTS FAVOURITES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    CONSTRAINT FK_FAVOURITES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UK_FAVOURITES_USER_PRODUCT UNIQUE (USER_ID, PRODUCT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_FAVOURITES_USER_ID ON FAVOURITES(USER_ID);

CREATE TABLE IF NOT EXISTS CART_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 1,
    CONSTRAINT FK_CART_ITEMS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UK_CART_ITEMS_USER_PRODUCT UNIQUE (USER_ID, PRODUCT_ID)
);

CREATE INDEX IF NOT EXISTS IDX_CART_ITEMS_USER_ID ON CART_ITEMS(USER_ID);

